---
- name: "Loki | Update packages"
  become: true
  apt:
    name: "{{ loki_additional_pkg }}"
    update_cache: yes

- name: "Loki | Create directory"
  become: true
  file:
    name: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ loki_temp_dir }}"
    - "{{ loki_etc_dir }}"

- name: "Loki | Download pre-compiled binary and unarchive it"
  become: true
  unarchive:
    src: "{{ loki_bin.url }}"
    dest: "{{ loki_temp_dir }}"
    remote_src: true
    creates: "{{ loki_temp_dir }}/{{ loki_bin.file }}"

- name: "Loki | Download config file"
  become: true
  get_url:
    url: "{{ loki_config.url }}"
    dest: "{{ loki_temp_dir }}/{{ loki_config.file }}"
    mode: '0440'
  
- name: "Loki | Move Loki files"
  become: true
  command: "mv {{ item.src }} {{ item.dest }}"
  with_items: 
    - src: "{{ loki_temp_dir }}/{{ loki_bin.file }}"
      dest: "{{ loki_bin.dir }}/"
    - src: "{{ loki_temp_dir }}/{{ loki_config.file }}"
      dest: "{{ loki_etc_dir }}/"

- include_tasks: run_as_service.yml